### ISSUE TITLE
Deduplicate issues for the same dependency

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/actor-repo-issue#4]
When the project has more than one `package.json`, sometimes duplicate issues are created:
https://github.com/storybooks/storybook/issues/2160
https://github.com/storybooks/storybook/issues/2161

Ideally, this should be one issue with a list of `package.json` locations where the dependency is used (actually, that info is useful even when there's only one such package)

**Comment by davegaeddert** [comment]
@Hypnosphi so is this coming from your lerna collector?

**Comment by Hypnosphi** [comment]
In this case, yes. But this also can be an issue when you just have more than one npm collector

**Comment by davegaeddert** [comment]
Ok. In the lerna case, it will be a lot easier to deal with this because all that information is present at the same time and run by the same actor. It would be a little harder to solve in the npm case (or other typical collectors) because they all run independently...we could maybe do something where we search and find existing open issues to update or comment on, but I'm not sure if we'll go that far or not right now.

**Comment by Hypnosphi** [comment]
> It would be a little harder to solve in the npm case
One thing that can be done is mentioning package.json location in issue if it's non-root

**Comment by davegaeddert** [comment]
This won't happen on this repo, but we will do it when we implement issues in the new components.
