### ISSUE TITLE
exec user process caused "argument list too long"

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/actor-repo-issue#7]
I'm getting a build error saying dependencies/actor-repo-issue:0.3.0 failed with the only line in the log being:
`standard_init_linux.go:178: exec user process caused "argument list too long"`

**Comment by davegaeddert** [comment]
Hey @Harmon758, it looks like the issue was that lxml names their git tags as `lxml-1.0.0` which threw off our changelog parsing. It resulted in a really long changelog which we weren't able to pass through the system. We've added this kind of tag format to our changelog parsing, and the "argument list too long" error is about to be fixed as soon as we push out the major update we're working on. In any case, I ran a new build on your repo and it looks like it's working again.

Thanks!
